### ISSUE TITLE
Listen in Tabellen werden nicht korrekt dargestellt

### ISSUE THREAD

**Issue by cstuder** [DokChess/website_de#2]
Beispiel: In [03_stakeholder.md](https://github.com/DokChess/website_de/blob/master/content/01_einfuehrung/03_stakeholder.md) wird das HTML herausgefiltert und danach als Fliesstext anstelle einer Liste auf der Seite [Stakeholder](https://www.dokchess.de/01_einfuehrung/03_stakeholder/) dargestellt.

**Comment by StefanZoerner** [comment]
Guter Punkt. Hintergrund ist eine Änderung in Hugo, siehe zum Beispiel hier:
https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
Ich habe den Renderer jetzt so konfiguriert, dass er das HTMl nicht rausfischt. Noch nicht die perfekte Lösung für die Tabellen. Aber für den Moment tut es denke ich, kann man die Aufzählungen wieder lesen.

**Comment by StefanZoerner** [comment]
Für den Moment behoben mit [diesem Commit](https://github.com/DokChess/website_de/commit/d0f2a3cc23cf3992a38ad6919e8d19eae4bcdbdd).

Die [Seite dem den Stakeholdern](https://www.dokchess.de/01_einfuehrung/03_stakeholder/#13-stakeholder) ist dann heile, und andere ähnlich gestrickte auch. 

Danke für den Hinweis, Christian!

**Comment by cstuder** [comment]
Das ging schnell. :-)

Sieht lesbarer aus, danke.
